# Generated by Django 5.2 on 2025-05-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField()),
                ('key_owner', models.CharField()),
                ('key_used', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
