# Generated by Django 5.2 on 2025-05-06 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_advisor_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='API_Usage',
            new_name='API',
        ),
    ]
