# Generated by Django 5.2 on 2025-05-06 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itinerary_app', '0003_itinerary_stay'),
        ('trip_app', '0002_trip_end_date_trip_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('image_thumb', models.CharField(blank=True, null=True)),
                ('image_main', models.CharField(blank=True, null=True)),
                ('location_id', models.CharField(blank=True, null=True)),
                ('category', models.CharField(blank=True, null=True)),
                ('itineraries', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='itinerary_app.itinerary')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='trip_app.trip')),
            ],
        ),
    ]
