# Generated by Django 5.2 on 2025-05-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('image_thumb', models.CharField(blank=True, null=True)),
                ('image_main', models.CharField(blank=True, null=True)),
                ('location_id', models.CharField(blank=True, null=True)),
                ('category', models.CharField(blank=True, null=True)),
            ],
        ),
    ]
