
# Generated by Django 5.2 on 2025-04-29 01:08

# Generated by Django 5.0.3 on 2025-04-29 15:58


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itinerary_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('itineraries', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='itinerary_app.itinerary')),
            ],
        ),
    ]
