# Generated by Django 5.2 on 2025-04-28 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_app', '0001_initial'),
        ('itinerary_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='itinerary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='itinerary_app.itinerary'),
            preserve_default=False,
        ),
    ]
