# Generated by Django 5.2 on 2025-05-06 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_app', '0001_initial'),
        ('itinerary_app', '0001_initial'),
        ('trip_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='image_main',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='image_thumb',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='location_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='trip_app.trip'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='itineraries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='itinerary_app.itinerary'),
        ),
    ]
