# Generated by Django 5.2 on 2025-05-07 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='itineraries',
        ),
    ]
