# Generated by Django 5.2 on 2025-05-06 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='itineraries',
        ),
    ]
