# Generated by Django 5.2 on 2025-05-06 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_app', '0002_remove_activity_itineraries'),
        ('trip_app', '0002_trip_end_date_trip_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='trip_app.trip'),
            preserve_default=False,
        ),
    ]
