# Generated by Django 5.2 on 2025-05-06 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_app', '0002_activity_image_main_activity_image_thumb_and_more'),
        ('trip_app', '0002_trip_end_date_trip_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='trip_app.trip'),
        ),
    ]
