# Generated by Django 5.2 on 2025-04-28 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_app', '0002_activity_itineraries'),
        ('activity_app', '0002_activity_itinerary'),
    ]

    operations = [
    ]
