# Generated by Django 5.2 on 2025-04-28 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_app', '0003_merge_20250428_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='itinerary',
        ),
    ]
