from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from itinerary_app.models import Itinerary

class Activity(models.Model):
  name = models.CharField(max_length=50, null=False, blank=False)
  location = models.CharField(max_length=100, null=True, blank=True)
  address = models.CharField(max_length=100, null=True, blank=True)
  url = models.URLField(null=True, blank=True)
  # itineraries = models.ForeignKey(Itinerary, on_delete=models.CASCADE, related_name="activities")
  # itinerary field will be generated by the Itinerary App Model

  def __repr__(self):
    return f" The activity: {self.name} at {self.address}, {self.location}. Link: {self.url}"
# Don't need to add the day/itinerary # because each activity will belong to one day/itinerary