from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models

class Activity(models.Model):
  name = models.CharField(max_length=50, null=False, blank=False)
  location = models.CharField(max_length=100, null=True, blank=True)
  address = models.CharField(max_length=100, null=True, blank=True)
  url = models.URLField(null=True, blank=True)
  # itinerary field will be generated by the Itinerary App Model

# Don't need to add the day/itinerary # because each activity will belong to one day/itinerary