# Generated by Django 5.2 on 2025-05-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0003_alter_trip_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='lat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='lng',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
