# Generated by Django 5.2 on 2025-05-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0004_trip_lat_trip_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
