# Generated by Django 5.2 on 2025-05-09 14:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('activities', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=21)),
            ],
        ),
    ]
