# Generated by Django 5.2 on 2025-05-06 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary_app', '0001_initial'),
        ('trip_app', '0002_trip_end_date_trip_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='trip_app.trip'),
            preserve_default=False,
        ),
    ]
