# Generated by Django 5.2 on 2025-05-08 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itinerary_app', '0001_initial'),
        ('stay_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='stay',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stay', to='stay_app.stay'),
        ),
    ]
