# Generated by Django 5.2 on 2025-05-07 19:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='activities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, max_length=21, size=300),
        ),
    ]
