# Generated by Django 5.2 on 2025-05-06 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary_app', '0002_itinerary_trip'),
        ('stay_app', '0004_stay_trip_alter_stay_itinerary'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='stay',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stay', to='stay_app.stay'),
        ),
    ]
