# Generated by Django 5.2 on 2025-05-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=120)),
                ('location', models.CharField(default='location', max_length=120)),
                ('link', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('image_thumb', models.CharField(blank=True, null=True)),
                ('image_main', models.CharField(blank=True, null=True)),
                ('location_id', models.CharField(blank=True, null=True)),
            ],
        ),
    ]
