# Generated by Django 5.2 on 2025-05-07 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trip_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=120)),
                ('location', models.CharField(default='location', max_length=120)),
                ('duration', models.PositiveIntegerField(default=3)),
                ('link', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('image_thumb', models.CharField(blank=True, null=True)),
                ('image_main', models.CharField(blank=True, null=True)),
                ('location_id', models.CharField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stay', to='trip_app.trip')),
            ],
        ),
    ]
