# Generated by Django 5.2 on 2025-04-28 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itinerary_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=120)),
                ('location', models.CharField(default='location', max_length=120)),
                ('duration', models.PositiveIntegerField(default=3, max_length=2)),
                ('link', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('itineraries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='itinerary_app.itinerary')),
            ],
        ),
    ]
