# Generated by Django 5.2 on 2025-05-09 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stay_app', '0001_initial'),
        ('trip_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stay', to='trip_app.trip'),
        ),
    ]
