# Generated by Django 5.2 on 2025-05-09 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stay_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stay',
            name='duration',
        ),
    ]
