# Generated by Django 5.2 on 2025-04-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='image_main',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stay',
            name='image_thumb',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stay',
            name='location_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
