# Generated by Django 5.2 on 2025-04-28 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary_app', '0001_initial'),
        ('stay_app', '0002_remove_stay_itineraries_stay_itinerary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stay',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='itinerary_app.itinerary'),
        ),
    ]
