# Generated by Django 5.2 on 2025-05-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay_app', '0002_stay_image_main_stay_image_thumb_stay_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stay',
            name='duration',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
