# Generated by Django 5.2 on 2025-04-29 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary_app', '0001_initial'),
        ('stay_app', '0003_alter_stay_itinerary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stay',
            name='itinerary',
        ),
        migrations.AddField(
            model_name='stay',
            name='ininerary',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='stays', to='itinerary_app.itinerary'),
            preserve_default=False,
        ),
    ]
