# Generated by Django 5.2 on 2025-05-06 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary_app', '0002_itinerary_trip'),
        ('stay_app', '0003_alter_stay_duration'),
        ('trip_app', '0002_trip_end_date_trip_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stays', to='trip_app.trip'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stay',
            name='itinerary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stays', to='itinerary_app.itinerary'),
        ),
    ]
