# Generated by Django 5.2 on 2025-04-29 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stay_app', '0004_remove_stay_itinerary_stay_ininerary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stay',
            old_name='ininerary',
            new_name='itinerary',
        ),
    ]
