# Generated by Django 5.2 on 2025-05-06 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay_app', '0004_stay_trip_alter_stay_itinerary'),
        ('trip_app', '0002_trip_end_date_trip_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stay',
            name='itinerary',
        ),
        migrations.AlterField(
            model_name='stay',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stay', to='trip_app.trip'),
        ),
    ]
